language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
  - php: hhvm

branches:
  except:
    - gh-pages

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta2"
  - composer install
  # Queue (Beanstalkd)
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd


before_script:

  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # Configure custom domain
  echo "127.0.0.1 mydomain.local" | sudo tee --append /etc/hosts

  - beanstalkd -d -l 127.0.0.1 -p 11300
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 & > /dev/null
  - sleep 5
  #- "mysql -e 'create database codeception_test;'"
  #- psql -c 'create database codeception_test;' -U postgres
  #- php -S localhost:8000 -t tests/data/app &
  #- php -S localhost:8010 -t tests/data &

script:
  - "wget http://codeception.com/codecept.phar"
  - php ./codecept.phar build
  - php ./codecept.phar run # self tests
  - php ./codecept.phar run acceptance